Features/pf 2602 move to tiny mce
sitkatech/projectfirma pull request #817
Opened 2023-08-30 22:35 UTC by Adrickle

2023-08-31 01:17 UTC, tomkamin requested changes
I cant get any rich text editors to load, using the NCRP tenant to test.
This error is in the console:
Uncaught SyntaxError: missing } after property list

2023-08-31 01:17 UTC, tomkamin commented on Source/ProjectFirma.Web/Common/TinyMCEEditorExtensionTest.GenerateJavascriptWithAllOnOneRowNoMaximizeToolbarsTest.received.txt
you shouldn't commit the received file. running the unit test should generate this and match the approved version

2023-08-31 01:17 UTC, tomkamin commented on Source/ProjectFirma.Web/Controllers/FileResourceController.cs
> -        public ContentResult CkEditorUploadFileResource(FirmaPagePrimaryKey firmaPagePrimaryKey, CkEditorImageUploadViewModel viewModel)
With this function removed, along with the others from this file, how are file uploads handled?

2023-08-31 15:33 UTC, Adrickle commented on Source/ProjectFirma.Web/Common/TinyMCEEditorExtensionTest.GenerateJavascriptWithAllOnOneRowNoMaximizeToolbarsTest.received.txt
fixed!

2023-08-31 15:38 UTC, Adrickle commented on Source/ProjectFirma.Web/Controllers/FileResourceController.cs
> -        public ContentResult CkEditorUploadFileResource(FirmaPagePrimaryKey firmaPagePrimaryKey, CkEditorImageUploadViewModel viewModel)
TinyMCE doesn't separate the file data from the text data, so it doesn't need a separate table to store that info in the database. There is a way to force TinyMCE to use a custom file handler, but we don't use it any of the other projects we've switched to TinyMCE.

2023-08-31 15:39 UTC, Adrickle commented
> I cant get any rich text editors to load, using the NCRP tenant to test. This error is in the console: Uncaught SyntaxError: missing } after property list

This should be fixed now

2023-08-31 23:35 UTC, tomkamin commented on Source/ProjectFirma.Web/Controllers/FileResourceController.cs
> -        public ContentResult CkEditorUploadFileResource(FirmaPagePrimaryKey firmaPagePrimaryKey, CkEditorImageUploadViewModel viewModel)
We should document that and consider moving all images currently in rich text fields into the text field like tiny MCE does, then we can remove the DB tables storing the files.

2023-09-01 00:42 UTC, tomkamin requested changes
If you can, please use the tinyMCE nuget package. Otherwise looks good and can merge!

2023-09-02 01:05 UTC, tomkamin requested changes

2023-09-02 01:05 UTC, tomkamin commented on Source/ProjectFirma.Web/wwwroot/lib/tinymce/tinymce.js
I am not sure how tinymce got into a wwwroot folder, but it looks like it is installed twice.
I tested on my local, uninstalled TinyMCE from nuget which left the wwwroot folder around. So I manually deleted that and reinstalled TinyMCE using the nuget GUI.
I have a feeling it was due to your initial install using the command line. Lets remove the whole wwwroot folder. It is not needed.

2023-09-05 20:21 UTC, tomkamin approved these changes

2023-09-05 20:21 UTC, merged